/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'todzhang' at '17-3-13 下午8:20' with Gradle 2.13
 *
 * @author todzhang, @date 17-3-13 下午8:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
