/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'todzhang' at '17-1-21 下午8:41' with Gradle 2.13
 *
 * @author todzhang, @date 17-1-21 下午8:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
